// GENERATED by assets/generate-dungeon-tiles.js — do not edit.
// Frame indices into dungeon-tiles.png (walls + floors sampled from the Super
// Overhead Adventure 2 dungeon sheet). Regenerate with:
//   npm run assets:tiles

/** Every floor look the dungeon has. Room types map onto these in TileRenderer. */
export type FloorTheme = "stone" | "maze" | "shop" | "shrine" | "chest" | "boss";

export const FLOOR_VARIANT_FRAMES: Record<FloorTheme, readonly number[]> = {
  stone: [47],
  maze: [47],
  shop: [47],
  shrine: [47],
  chest: [47],
  boss: [47],
};

/** Wall frame for an 8-neighbour mask (bit 0 = N, then clockwise: NE E SE S SW W NW).
 *  A set bit means "that neighbour is also wall". Indexed by the raw 0–255 mask;
 *  the 256 -> 47 reduction is already folded in. */
export const WALL_FRAME_BY_MASK: readonly number[] = [
  0, 1, 0, 1, 2, 3, 2, 4, 0, 1, 0, 1, 2, 3, 2, 4,
  5, 6, 5, 6, 7, 8, 7, 9, 5, 6, 5, 6, 10, 11, 10, 12,
  0, 1, 0, 1, 2, 3, 2, 4, 0, 1, 0, 1, 2, 3, 2, 4,
  5, 6, 5, 6, 7, 8, 7, 9, 5, 6, 5, 6, 10, 11, 10, 12,
  13, 14, 13, 14, 15, 16, 15, 17, 13, 14, 13, 14, 15, 16, 15, 17,
  18, 19, 18, 19, 20, 21, 20, 22, 18, 19, 18, 19, 23, 24, 23, 25,
  13, 14, 13, 14, 15, 16, 15, 17, 13, 14, 13, 14, 15, 16, 15, 17,
  26, 27, 26, 27, 28, 29, 28, 30, 26, 27, 26, 27, 31, 32, 31, 33,
  0, 1, 0, 1, 2, 3, 2, 4, 0, 1, 0, 1, 2, 3, 2, 4,
  5, 6, 5, 6, 7, 8, 7, 9, 5, 6, 5, 6, 10, 11, 10, 12,
  0, 1, 0, 1, 2, 3, 2, 4, 0, 1, 0, 1, 2, 3, 2, 4,
  5, 6, 5, 6, 7, 8, 7, 9, 5, 6, 5, 6, 10, 11, 10, 12,
  13, 34, 13, 34, 15, 35, 15, 36, 13, 34, 13, 34, 15, 35, 15, 36,
  18, 37, 18, 37, 20, 38, 20, 39, 18, 37, 18, 37, 23, 40, 23, 41,
  13, 34, 13, 34, 15, 35, 15, 36, 13, 34, 13, 34, 15, 35, 15, 36,
  26, 42, 26, 42, 28, 43, 28, 44, 26, 42, 26, 42, 31, 45, 31, 46,
];

export const SPECIAL_FRAMES = {
  stairs: 48,
  trap: 49,
  bossFloor: 50,
  fire: 51,
  slime: 52,
  wallShadow: 53,
  barrier: 54,
} as const;
